seed: 1337
dialogParser:
  maxGapBetweenDialogs: 3
  fps: 24
  pathToSubtitles: 'D:\Programowanie\deep_learning\chatbox\data/subtitles'
word2vec:
  pathToInputFile: 'D:\Programowanie\deep_learning\chatbox\data/joinedFile.txt'
  models:
    pathToModel: 'D:\Programowanie\deep_learning\chatbox\data/models/word2vec.bin'
    pathToWordVectors: 'D:\Programowanie\deep_learning\chatbox\data/models/wordVectors.txt'
  hyper:
    minWordFrequency: 5
    iterations: 1
    layerSize: 300
    windowsSize: 5
subtitles:
  path: 'D:\Programowanie\deep_learning\chatbox\data/subtitles'
rnn:
  maxWordsInDialog: 30
  batchSize: 50
  epochs: 5
  regularization: true
  learningRate: 0.0018
  l2: 1e-5
  gradientNormalizationThreshold: 1.0
  layers:
    l0:
      nout: 200