seed: 1337
dialogLoader:
  maxGapBetweenDialogs: 3 # in secs
  fps: 24
  pathToSubtitles: 'D:\Programowanie\deep_learning\chatbox\data/subtitles'
word2vec:
  models:
    pathToModel: 'D:\Programowanie\deep_learning\chatbox\data/models/word2vec.bin'
    pathToWordVectors: 'D:\Programowanie\deep_learning\chatbox\data/models/wordVectors.txt'
  hyper:
    minWordFrequency: 5
    iterations: 1
    layerSize: 300
    windowsSize: 5
subtitles:
  path: 'D:\Programowanie\deep_learning\chatbox\data/subtitles'
rnn:
  iterations: 1
  maxWordsInDialog: 30
  batchSize: 50
  epochs: 30
  regularization: false
  learningRate: 0.1
  l2: 1e-5
  gradientNormalizationThreshold: 1.0
  layers:
    l0:
      nout: 200
  pathToSaveModel: 'D:\Programowanie\deep_learning\chatbox\data/models/rnn-model.bin'
iterationListeners:
  fileStatsStorage: 'D:\Programowanie\deep_learning\chatbox\data\ui_service.bin'
  printIterations: 200